#ifndef _CQ_TYPE
#define _CQ_TYPE

#include <stdint.h>

typedef int32_t cq_bool_t;

// 日志等级
#define DEBUG_LEVEL_DEBUG			0
#define DEBUG_LEVEL_INFO			10
#define DEBUG_LEVEL_INFO_SUCCESS	11
#define DEBUG_LEVEL_INFO_RECV		12
#define DEBUG_LEVEL_INFO_SEND		13
#define DEBUG_LEVEL_WARNING			20
#define DEBUG_LEVEL_ERROR			30
#define DEBUG_LEVEL_FATAL			40

#define SUBTYPE_PRIVATE_MESSAGE_FRIEND 11
#define SUBTYPE_PRIVATE_MESSAGE_ONLINE_STATE 1
#define SUBTYPE_PRIVATE_MESSAGE_GROUP 2
#define SUBTYPE_PRIVATE_MESSAGE_DISCUSSION_GROUP 3

#define SUBTYPE_GROUP_ADMIN_CANCEL 1
#define SUBTYPE_GROUP_ADMIN_SET 2

#define SUBTYPE_GROUP_MEMBER_DECREASE_LEAVE 1
#define SUBTYPE_GROUP_MEMBER_DECREASE_KICK 2
#define SUBTYPE_GROUP_MEMBER_DECREASE_BE_KICK 3

#define SUBTYPE_GROUP_MEMBER_INCREASE_AGREE 1
#define SUBTYPE_GROUP_MEMBER_INCREASE_INVITE 2

#define SUBTYPE_ADD_GROUP_REQUEST_OTHER 1
#define SUBTYPE_ADD_GROUP_REQUEST_YOU 2

#endif